### ISSUE TITLE
How to use the repository?

### ISSUE THREAD

**Issue by JafferWilson** [siddBanPsu/Paraphrasing#1]
Kindly mention how to use the paraphrasing repository of yours. Also would like to know whether it generates english paraphrases or it compares paraphrases and gives output?
Waiting for your answer.

**Comment by siddBanPsu** [comment]
@JafferWilson You can check the usage in this file src/sidd/SentenceReWriter.py
I will try to write up an extensive documentation if time permits.

**Comment by JafferWilson** [comment]
@siddBanPsu  Thank you for your kind words. But at least I think you should mention something in the READ.ME so making sense about what is the use. Atleast about running and data required. But anyways, Thank you once again
